import org.gradle.internal.os.OperatingSystem

pluginManagement {
	repositories {
		mavenLocal()
		gradlePluginPortal()
		String frcYear = '2026'
		File frcHome
		if (OperatingSystem.current().isWindows()) {
			String publicFolder = System.getenv('PUBLIC')
			if (publicFolder == null) {
				publicFolder = "C:\\Users\\Public"
			}
			def homeRoot = new File(publicFolder, "wpilib")
			frcHome = new File(homeRoot, frcYear)
		} else {
			def userFolder = System.getProperty("user.home")
			def homeRoot = new File(userFolder, "wpilib")
			frcHome = new File(homeRoot, frcYear)
		}
		def frcHomeMaven = new File(frcHome, 'maven')
		maven {
			name = 'frcHome'
			url = frcHomeMaven
		}
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
	id 'org.danilopianini.gradle-pre-commit-git-hooks' version '2.1.21'
}

gitHooks { extension ->
	extension.with {
		preCommit { context ->
			context.with {
				from(file('scripts/pre-commit.sh'))
			}
		}
		createHooks(true)
	}
}

Properties props = System.getProperties();
props.setProperty("org.gradle.internal.native.headers.unresolved.dependencies.ignore", "true");

rootProject.name = 'team581-frc-2026'

// Include all projects
include 'shared'
include 'refaster-rules'
include "comp-bot"
include "new-member-bot"
include "offseason-bot"
