package frc.robot.robot_manager;

public enum RobotState {
  IDLE,

  PREPARE_SCORE,
  SCORE,

  PREPARE_PRESET_SCORE,
  PRESET_SCORE,

  PREPARE_PRESET_FEED,
  PRESET_FEED,

  PREPARE_FEED,
  FEED,

  UNJAM,
  REHOME_DEPLOY,
  REHOME_SHOOTER_HOOD,

  CLIMB_1_LINEUP_L1_AUTONOMOUS,
  CLIMB_2_RAISING_L1_AUTONOMOUS,
  CLIMB_3_HANGING_L1_AUTONOMOUS,
  CLIMB_4_RELEASE_L1_AUTONOMOUS,

  AUTOMATIC_CLIMB_1_LINEUP_L1,
  AUTOMATIC_CLIMB_2_RAISING_L1,
  AUTOMATIC_CLIMB_3_HANGING_L1,

  AUTOMATIC_CLIMB_4_RAISING_L2,
  AUTOMATIC_CLIMB_5_HANGING_L2,

  AUTOMATIC_CLIMB_6_RAISING_L3,
  AUTOMATIC_CLIMB_7_HANGING_L3,

  MANUAL_CLIMB_1_LINEUP_L1,
  MANUAL_CLIMB_2_RAISING_L1,
  MANUAL_CLIMB_3_HANGING_L1,

  MANUAL_CLIMB_4_RAISING_L2,
  MANUAL_CLIMB_5_HANGING_L2,

  MANUAL_CLIMB_6_RAISING_L3,
  MANUAL_CLIMB_7_HANGING_L3;

  public boolean isClimbingOrRehoming() {
    return switch (this) {
      case CLIMB_1_LINEUP_L1_AUTONOMOUS -> true;
      case CLIMB_2_RAISING_L1_AUTONOMOUS -> true;
      case CLIMB_3_HANGING_L1_AUTONOMOUS -> true;

      case AUTOMATIC_CLIMB_1_LINEUP_L1 -> true;
      case AUTOMATIC_CLIMB_2_RAISING_L1 -> true;
      case AUTOMATIC_CLIMB_3_HANGING_L1 -> true;
      case AUTOMATIC_CLIMB_4_RAISING_L2 -> true;
      case AUTOMATIC_CLIMB_5_HANGING_L2 -> true;
      case AUTOMATIC_CLIMB_6_RAISING_L3 -> true;
      case AUTOMATIC_CLIMB_7_HANGING_L3 -> true;

      case MANUAL_CLIMB_1_LINEUP_L1 -> true;
      case MANUAL_CLIMB_2_RAISING_L1 -> true;
      case MANUAL_CLIMB_3_HANGING_L1 -> true;
      case MANUAL_CLIMB_4_RAISING_L2 -> true;
      case MANUAL_CLIMB_5_HANGING_L2 -> true;
      case MANUAL_CLIMB_6_RAISING_L3 -> true;
      case MANUAL_CLIMB_7_HANGING_L3 -> true;

      case REHOME_DEPLOY -> true;
      case REHOME_SHOOTER_HOOD -> true;

      default -> false;
    };
  }
}
