package frc.robot.autos.auto_state_machines.auto_state;

import com.google.common.collect.ImmutableMap;

public enum IntegrationTestState {
  SEGMENT_1_DRIVE_TO_START,
  SEGMENT_2_CLOSE_CENTERED_WITH_HUB,
  SEGMENT_2_CLOSE_CENTERED_WITH_HUB_SCORE,
  SEGMENT_3_BACK_CENTERED_WITH_HUB,
  SEGMENT_3_BACK_CENTERED_WITH_HUB_SCORE,
  SEGMENT_4_RIGHT_TRENCH,
  SEGMENT_4_RIGHT_TRENCH_SCORE,
  SEGMENT_5_RIGHT_CORNER,
  SEGMENT_5_RIGHT_CORNER_SCORE,
  SEGMENT_6_SCORE_ON_THE_MOVE_LEFT_BUMP;

  private static final ImmutableMap<IntegrationTestState, IntegrationTestState> NEXT_STATE =
      ImmutableMap.of(
          SEGMENT_1_DRIVE_TO_START,
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB,
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB,
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB_SCORE,
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB_SCORE,
          SEGMENT_3_BACK_CENTERED_WITH_HUB,
          SEGMENT_3_BACK_CENTERED_WITH_HUB,
          SEGMENT_3_BACK_CENTERED_WITH_HUB_SCORE,
          SEGMENT_3_BACK_CENTERED_WITH_HUB_SCORE,
          SEGMENT_4_RIGHT_TRENCH,
          SEGMENT_4_RIGHT_TRENCH,
          SEGMENT_4_RIGHT_TRENCH_SCORE,
          SEGMENT_4_RIGHT_TRENCH_SCORE,
          SEGMENT_5_RIGHT_CORNER,
          SEGMENT_5_RIGHT_CORNER,
          SEGMENT_5_RIGHT_CORNER_SCORE,
          SEGMENT_5_RIGHT_CORNER_SCORE,
          SEGMENT_6_SCORE_ON_THE_MOVE_LEFT_BUMP);

  private static final ImmutableMap<IntegrationTestState, IntegrationTestState> PREVIOUS_STATE =
      ImmutableMap.of(
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB,
          SEGMENT_1_DRIVE_TO_START,
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB_SCORE,
          SEGMENT_1_DRIVE_TO_START,
          SEGMENT_3_BACK_CENTERED_WITH_HUB,
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB,
          SEGMENT_3_BACK_CENTERED_WITH_HUB_SCORE,
          SEGMENT_2_CLOSE_CENTERED_WITH_HUB,
          SEGMENT_4_RIGHT_TRENCH,
          SEGMENT_3_BACK_CENTERED_WITH_HUB,
          SEGMENT_4_RIGHT_TRENCH_SCORE,
          SEGMENT_3_BACK_CENTERED_WITH_HUB,
          SEGMENT_5_RIGHT_CORNER,
          SEGMENT_4_RIGHT_TRENCH,
          SEGMENT_5_RIGHT_CORNER_SCORE,
          SEGMENT_4_RIGHT_TRENCH);

  public IntegrationTestState nextState() {
    return NEXT_STATE.getOrDefault(this, this);
  }

  public IntegrationTestState previousState() {
    return PREVIOUS_STATE.getOrDefault(this, this);
  }
}
