package frc.robot.autos.auto_state_machines.auto_state;

public enum TrenchMidlineFeedAutoState {
  SEGMENT_1_DRIVE_TO_MIDLINE,
  INTAKE_ACROSS_MIDLINE_1,
  INTAKE_ACROSS_MIDLINE_2,
  SEGMENT_2_DRIVE_TO_FEED_1,
  SEGMENT_3_DRIVE_TO_FEED_2,
  FEED_1,
  FEED_2,
  SEGMENT_4_DRIVE_BACK,
  SEGMENT_5_INTAKE_ALLIANCE_SIDE,
  SEGMENT_6_DRIVE_TO_SHOOT,
  SHOOT,
  DONE;
}
