[project]
name = "cad"
version = "0.0.0"
description = "Tools for converting CAD exports to AdvantageScope assets"
requires-python = ">=3.14"
dependencies = ["cadquery-ocp==8.0.1.0.0", "numpy==2.5.3", "scipy==1.18.1", "trimesh==5.1.1"]

[dependency-groups]
dev = ["ty"]

[tool.ty.environment]
python-version = "3.14"

[tool.ty.src]
include = ["**/*.py"]
