plugins {
	id "edu.wpi.first.GradleRIO"
}

// Defining my dependencies. In this case, WPILib (+ friends), and vendor libraries.
// Also defines JUnit 5.
dependencies {
	annotationProcessor wpi.java.deps.wpilibAnnotations()
	implementation wpi.java.deps.wpilib()
	implementation wpi.java.vendor.java()

	// Native JNI libraries for desktop testing
	nativeDebug wpi.java.deps.wpilibJniDebug(wpi.platforms.desktop)
	nativeDebug wpi.java.vendor.jniDebug(wpi.platforms.desktop)
	nativeRelease wpi.java.deps.wpilibJniRelease(wpi.platforms.desktop)
	nativeRelease wpi.java.vendor.jniRelease(wpi.platforms.desktop)

	testImplementation 'org.junit.jupiter:junit-jupiter:6.0.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// https://central.sonatype.com/artifact/com.google.guava/guava
	implementation 'com.google.guava:guava:33.5.0-jre'

	// https://central.sonatype.com/artifact/org.apache.commons/commons-geometry-euclidean
	implementation 'org.apache.commons:commons-geometry-euclidean:1.0'

	// https://central.sonatype.com/artifact/org.hipparchus/hipparchus-geometry
	implementation 'org.hipparchus:hipparchus-geometry:4.0.3'

	// https://central.sonatype.com/artifact/org.hipparchus/hipparchus-fitting
	implementation 'org.hipparchus:hipparchus-fitting:4.0.3'
}

ext.wpilibVersion = "2026.+"

// Enable desktop support for shared library
wpi.java.configureTestTasks(test)
