plugins {
	id "edu.wpi.first.GradleRIO"
}

// Defining my dependencies. In this case, WPILib (+ friends), and vendor libraries.
// Also defines JUnit 5.
dependencies {
	annotationProcessor wpi.java.deps.wpilibAnnotations()
	implementation wpi.java.deps.wpilib()
	implementation wpi.java.vendor.java()

	testImplementation 'org.junit.jupiter:junit-jupiter:6.0.2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// https://central.sonatype.com/artifact/com.google.guava/guava
	implementation 'com.google.guava:guava:33.5.0-jre'
}

ext.wpilibVersion = "2026.+"

// Enable desktop support for shared library
wpi.java.configureTestTasks(test)
