name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Ruff
        uses: astral-sh/ruff-action@v3

      - name: Fix Error Prone issues
        run: ./gradlew build
        continue-on-error: true
        env:
          ERRORPRONE_AUTOFIX: 1

      - name: Format with Spotless
        run: ./gradlew spotlessApply
        continue-on-error: true

      - name: Fix Python lint issues with Ruff
        run: ruff check --fix --unsafe-fixes
        continue-on-error: true

      - name: Format Python with Ruff
        run: ruff format
        continue-on-error: true

      - name: Run autofix.ci
        uses: autofix-ci/action@v1
