name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  validation:
    name: Validate Gradle wrappers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6
      - name: Validate Gradle wrappers
        uses: gradle/actions/wrapper-validation@v5
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    needs:
      - validation
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"

      - name: Fix Error Prone issues
        run: ./gradlew build
        continue-on-error: true
        env:
          ERRORPRONE_AUTOFIX: 1

      - name: Format with Spotless
        run: ./gradlew spotlessApply
        continue-on-error: true

      - name: Fix Python lint issues with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --fix"
        continue-on-error: true

      - name: Format Python with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format"
        continue-on-error: true

      - name: Run autofix.ci
        uses: autofix-ci/action@v1
